os: linux
dist: xenial

language: node_js
node_js:
  - "16"

# Commands to install dependencies
install:
  - npm install

# Commands to run tests
script:
  - echo "Hello, Ok test"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
